# Even Fibonacci numbers
# Problem 2
#
# https://projecteuler.net/problem=2
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

rolling_count = 0

def fibonacci(prev, current):
    global rolling_count
    if current > 4000000:
        return rolling_count
    if current % 2 == 0:
        rolling_count = rolling_count + current
    fibonacci(current, prev+current)

fibonacci(0,1)
print rolling_count